### PR TITLE
Modifications to `remap_player_names` and introduction of `remap_player_info`

### PR DESCRIPTION
**Pull request by awosoga**
I have modified `remap_player_names` to change the `firstname` and `lastname` columns via  a simple `str_split` and  use `dplyr::update_rows` to update the  `players_h\v` dataframes accordingly. I can use a base r variant of `update_rows` should that be requested. These changes will now make it into `dv_write`. Names like "John Paul Doe" will be mapped as "John" and "Paul Doe", so in order to give the user full control over all player information edits, I propose a new function, which I call `remap_player_info`. It requires stricter argument inputs but can remap both names and player id's, and make the associated changes to player id's in the `plays` dataframe as well. I think it can eventually replace `remap_player_names`. Happy to give more explanation and clarification about the process.

### CODE REVIEW

**Comment by awosoga** [comment]
They line from the original function to "enforce all cols to be character" can be quite troublesome, and it might be best for it to be commented out entirely from both functions. I kept them here for consistency with the original code

**Comment by raymondben** [comment]
@awosoga what's the issue with enforcing those cols to be character?

**Comment by awosoga** [comment]
@raymondben 

It works with `data.frame` objects, but not with `tibbles`. For example:

```
remap <- data.frame(team=c("Nova KBM Branik","Braslovče"),
       name_from=c("ELA PINTAR","KATJA MIHALINEC"),
       firstname=c("Ela","Katja"), stringsAsFactors=FALSE))
```

returns 

```
             team       name_from firstname
1 Nova KBM Branik      ELA PINTAR       Ela
2       Braslovče KATJA MIHALINEC     Katja
```

from `for (k in seq_len(ncol(remap))) remap[,k] <- as.character(remap[,k])`, as expected. However, 

```
remap <- tibble(team=c("Nova KBM Branik","Braslovče"),
       name_from=c("ELA PINTAR","KATJA MIHALINEC"),
       firstname=c("Ela","Katja"))
```

returns 

```
  team                                    name_from                                firstname              
  <chr>                                   <chr>                                    <chr>                  
1 "c(\"Nova KBM Branik\", \"Braslovče\")" "c(\"ELA PINTAR\", \"KATJA MIHALINEC\")" "c(\"Ela\", \"Katja\")"
2 "c(\"Nova KBM Branik\", \"Braslovče\")" "c(\"ELA PINTAR\", \"KATJA MIHALINEC\")" "c(\"Ela\", \"Katja\")"

```

after the character enforcement code is ran.

So with `data.frame` objects, both remapping functions work just fine, but with `tibbles` it throws an error in `remap_player_info` and silently doesn't work in the original `remap_player_names` (`mapvalues` has no matches, so nothing changes). I suppose the quick fix would be to coerce `remap` to a data.frame using `as.data.frame`. That would solve things

**Comment by raymondben** [comment]
Ah, of course (it's because `x[, k]` returns the kth column of a data.frame, but a 1-column tibble for a tibble. I'd forgotten that). Thanks.
Easily fixed by indexing as `x[[k]]` (returns the kth column for both) or a dplyr `mutate(across(everything(), ...))` style replacement.

**Pull request merged**
